### ISSUE TITLE
Unannotated version of House Rules

### ISSUE THREAD

**Issue by DanielSchuman** [usgpo/house-manual#1]
Thank you for posting the House Rules on GitHub and in a structured data format. 

Is it possible to post a "clean" version of the House Rules--ones that do not have any annotations.but just the text of the rules themselves?

**Comment by mangiafico** [comment]
see /114/govinfo-file-names/GPO-CLERK-RULE-PAMPHLET-114.xml

**Comment by llaplant** [comment]
also
/114/original-file-names/rules_clerk.xml

**Comment by GullicksonK** [comment]
Daniel, 

This might also be helpful.

•         Download the zip, and unzip it
•         Using Windows Explorer, if you are in an Windows,  explore to the “114” folder, then the “original-file-names” folder
•         Right click on the file “rules.xml” and use “open with” and select one of your browsers
•         The file should open in the browser

The other fun thing to open would be “toc.xml”.  It provides clickable links to the files that comprise the House Manual itself.

Let us know what you think about it all.

**Comment by DanielSchuman** [comment]
AHA!

@llaplant 's approach worked for me. This file -- /114/original-file-names/rules_clerk.xml  (more specifically: -- displays the House Rules with no annotations in a human readable format (i.e formatted).

@magianifico 's approach is close but doesn't quite get me there. This file -- /114/govinfo-file-names/GPO-CLERK-RULE-PAMPHLET-114.xml -- is indeed the House rules without annotations, but also without any styling, so the text runs together. Useful for a diff, but not human readable.

@GullicksonK 's  approach didn't quite work for me. I got the file to display with styling-- and it looks good -- but it contained the annotations (notes) that I'm trying to avoid.

For replication's sake, this is my more verbose, n00b's like effort to follow Kirsten's instructions: 
1. Go to https://github.com/usgpo/house-manual
2. On the right side of the menu bar, click on "Download Zip"
3. Once downloaded, extract the files
4. Open the file folder that's been extracted and go: house-manual-master >>114 >>original file names >> rules.xml
5. Open the file with Internet Explorer or Firefox. It likely will not display on Chrome (don't know about Safari). (May have to assign a browser to do this)

```

The TOC file is a useful way to get to specific rules, but it still has the notes included.

Thank you everyone.
```

**Comment by jonquandt** [comment]
@DanielSchuman -- I just merged a pull request from @mangiafico that fixes the styling issue you saw with the GPO-CLERK-RULE-PAMPHLET-114.xml. That should close out this issue.

Note that when this releases officially on FDsys/govinfo, the unannotated version (GPO-CLERK-RULE-PAMPHLET-114.xml) will be available in a separate package from the House Manual XML bulk download. That version won't be in the bulk data download. 

When it goes live, I'll add a link to it in the readme, but the filename is the package name.
